'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace SunatCDRSE
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://service.sunat.gob.pe", ConfigurationName:="SunatCDRSE.billService")>  _
    Public Interface billService
        
        'CODEGEN: Parameter 'status' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        <System.ServiceModel.OperationContractAttribute(Action:="urn:getStatus", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function getStatus(ByVal request As SunatCDRSE.getStatusRequest) As <System.ServiceModel.MessageParameterAttribute(Name:="status")> SunatCDRSE.getStatusResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="urn:getStatus", ReplyAction:="*")>  _
        Function getStatusAsync(ByVal request As SunatCDRSE.getStatusRequest) As System.Threading.Tasks.Task(Of SunatCDRSE.getStatusResponse)
        
        'CODEGEN: Parameter 'statusCdr' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        <System.ServiceModel.OperationContractAttribute(Action:="urn:getStatusCdr", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function getStatusCdr(ByVal request As SunatCDRSE.getStatusCdrRequest) As <System.ServiceModel.MessageParameterAttribute(Name:="statusCdr")> SunatCDRSE.getStatusCdrResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="urn:getStatusCdr", ReplyAction:="*")>  _
        Function getStatusCdrAsync(ByVal request As SunatCDRSE.getStatusCdrRequest) As System.Threading.Tasks.Task(Of SunatCDRSE.getStatusCdrResponse)
    End Interface
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://service.sunat.gob.pe")>  _
    Partial Public Class statusResponse
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private contentField() As Byte
        
        Private statusCodeField As String
        
        Private statusMessageField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="base64Binary", Order:=0)>  _
        Public Property content() As Byte()
            Get
                Return Me.contentField
            End Get
            Set
                Me.contentField = value
                Me.RaisePropertyChanged("content")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property statusCode() As String
            Get
                Return Me.statusCodeField
            End Get
            Set
                Me.statusCodeField = value
                Me.RaisePropertyChanged("statusCode")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=2)>  _
        Public Property statusMessage() As String
            Get
                Return Me.statusMessageField
            End Get
            Set
                Me.statusMessageField = value
                Me.RaisePropertyChanged("statusMessage")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="getStatus", WrapperNamespace:="http://service.sunat.gob.pe", IsWrapped:=true)>  _
    Partial Public Class getStatusRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://service.sunat.gob.pe", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public rucComprobante As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://service.sunat.gob.pe", Order:=1),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public tipoComprobante As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://service.sunat.gob.pe", Order:=2),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public serieComprobante As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://service.sunat.gob.pe", Order:=3),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public numeroComprobante As Integer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal rucComprobante As String, ByVal tipoComprobante As String, ByVal serieComprobante As String, ByVal numeroComprobante As Integer)
            MyBase.New
            Me.rucComprobante = rucComprobante
            Me.tipoComprobante = tipoComprobante
            Me.serieComprobante = serieComprobante
            Me.numeroComprobante = numeroComprobante
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="getStatusResponse", WrapperNamespace:="http://service.sunat.gob.pe", IsWrapped:=true)>  _
    Partial Public Class getStatusResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://service.sunat.gob.pe", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public status As SunatCDRSE.statusResponse
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal status As SunatCDRSE.statusResponse)
            MyBase.New
            Me.status = status
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="getStatusCdr", WrapperNamespace:="http://service.sunat.gob.pe", IsWrapped:=true)>  _
    Partial Public Class getStatusCdrRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://service.sunat.gob.pe", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public rucComprobante As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://service.sunat.gob.pe", Order:=1),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public tipoComprobante As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://service.sunat.gob.pe", Order:=2),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public serieComprobante As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://service.sunat.gob.pe", Order:=3),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public numeroComprobante As Integer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal rucComprobante As String, ByVal tipoComprobante As String, ByVal serieComprobante As String, ByVal numeroComprobante As Integer)
            MyBase.New
            Me.rucComprobante = rucComprobante
            Me.tipoComprobante = tipoComprobante
            Me.serieComprobante = serieComprobante
            Me.numeroComprobante = numeroComprobante
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="getStatusCdrResponse", WrapperNamespace:="http://service.sunat.gob.pe", IsWrapped:=true)>  _
    Partial Public Class getStatusCdrResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://service.sunat.gob.pe", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public statusCdr As SunatCDRSE.statusResponse
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal statusCdr As SunatCDRSE.statusResponse)
            MyBase.New
            Me.statusCdr = statusCdr
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface billServiceChannel
        Inherits SunatCDRSE.billService, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class billServiceClient
        Inherits System.ServiceModel.ClientBase(Of SunatCDRSE.billService)
        Implements SunatCDRSE.billService
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function SunatCDRSE_billService_getStatus(ByVal request As SunatCDRSE.getStatusRequest) As SunatCDRSE.getStatusResponse Implements SunatCDRSE.billService.getStatus
            Return MyBase.Channel.getStatus(request)
        End Function
        
        Public Function getStatus(ByVal rucComprobante As String, ByVal tipoComprobante As String, ByVal serieComprobante As String, ByVal numeroComprobante As Integer) As SunatCDRSE.statusResponse
            Dim inValue As SunatCDRSE.getStatusRequest = New SunatCDRSE.getStatusRequest()
            inValue.rucComprobante = rucComprobante
            inValue.tipoComprobante = tipoComprobante
            inValue.serieComprobante = serieComprobante
            inValue.numeroComprobante = numeroComprobante
            Dim retVal As SunatCDRSE.getStatusResponse = CType(Me,SunatCDRSE.billService).getStatus(inValue)
            Return retVal.status
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function SunatCDRSE_billService_getStatusAsync(ByVal request As SunatCDRSE.getStatusRequest) As System.Threading.Tasks.Task(Of SunatCDRSE.getStatusResponse) Implements SunatCDRSE.billService.getStatusAsync
            Return MyBase.Channel.getStatusAsync(request)
        End Function
        
        Public Function getStatusAsync(ByVal rucComprobante As String, ByVal tipoComprobante As String, ByVal serieComprobante As String, ByVal numeroComprobante As Integer) As System.Threading.Tasks.Task(Of SunatCDRSE.getStatusResponse)
            Dim inValue As SunatCDRSE.getStatusRequest = New SunatCDRSE.getStatusRequest()
            inValue.rucComprobante = rucComprobante
            inValue.tipoComprobante = tipoComprobante
            inValue.serieComprobante = serieComprobante
            inValue.numeroComprobante = numeroComprobante
            Return CType(Me,SunatCDRSE.billService).getStatusAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function SunatCDRSE_billService_getStatusCdr(ByVal request As SunatCDRSE.getStatusCdrRequest) As SunatCDRSE.getStatusCdrResponse Implements SunatCDRSE.billService.getStatusCdr
            Return MyBase.Channel.getStatusCdr(request)
        End Function
        
        Public Function getStatusCdr(ByVal rucComprobante As String, ByVal tipoComprobante As String, ByVal serieComprobante As String, ByVal numeroComprobante As Integer) As SunatCDRSE.statusResponse
            Dim inValue As SunatCDRSE.getStatusCdrRequest = New SunatCDRSE.getStatusCdrRequest()
            inValue.rucComprobante = rucComprobante
            inValue.tipoComprobante = tipoComprobante
            inValue.serieComprobante = serieComprobante
            inValue.numeroComprobante = numeroComprobante
            Dim retVal As SunatCDRSE.getStatusCdrResponse = CType(Me,SunatCDRSE.billService).getStatusCdr(inValue)
            Return retVal.statusCdr
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function SunatCDRSE_billService_getStatusCdrAsync(ByVal request As SunatCDRSE.getStatusCdrRequest) As System.Threading.Tasks.Task(Of SunatCDRSE.getStatusCdrResponse) Implements SunatCDRSE.billService.getStatusCdrAsync
            Return MyBase.Channel.getStatusCdrAsync(request)
        End Function
        
        Public Function getStatusCdrAsync(ByVal rucComprobante As String, ByVal tipoComprobante As String, ByVal serieComprobante As String, ByVal numeroComprobante As Integer) As System.Threading.Tasks.Task(Of SunatCDRSE.getStatusCdrResponse)
            Dim inValue As SunatCDRSE.getStatusCdrRequest = New SunatCDRSE.getStatusCdrRequest()
            inValue.rucComprobante = rucComprobante
            inValue.tipoComprobante = tipoComprobante
            inValue.serieComprobante = serieComprobante
            inValue.numeroComprobante = numeroComprobante
            Return CType(Me,SunatCDRSE.billService).getStatusCdrAsync(inValue)
        End Function
    End Class
End Namespace
